### ISSUE TITLE
Wheel.lua causing unbearable errors and SLG(LUVM) settings menu crashes the game + others

### ISSUE THREAD

**Issue by ImDarkener** [The-Grace-God/Simply-Love-NotITG#7]
When attempting to open the SLG(LUVM) menu the game instantly crashes not even an error comes up
[crashinfo-1684289943.txt](https://github.com/The-Grace-God/Simply-Love-NotITG/files/11493575/crashinfo-1684289943.txt)

I get this error when the level select opens
![NotITG-v4 2 0_CBK8hOmTfT](https://github.com/The-Grace-God/Simply-Love-NotITG/assets/72986437/342f3905-00a4-4fee-8f52-7ea86bb7f2f9)
It seems to do this every time the level select is updated while a level is on screen, 
If i go over to a section without any open levels there is no error and i can scroll freely
The moment one is on screen it starts spamming the errors again and it locks one of the direction keys till their off screen again

There was also a thing about a command string that sometimes shows up when starting a level, but it seems random
![image](https://github.com/The-Grace-God/Simply-Love-NotITG/assets/72986437/2464dc0a-2135-4ca7-8ce0-33a9248c87b2)

And also this error comes up when the loading the end screen
![NotITG-v4 2 0_AZtfmyKynR](https://github.com/The-Grace-God/Simply-Love-NotITG/assets/72986437/07e339a5-126d-48f7-9492-981baa51e345)

**Comment by ImDarkener** [comment]
Turns out whatever was wrong is fixed in 9.1
I only had 9 since it said it was the latest
Besides the issues with the Theme settings menu crashing, thats still happening.

**Comment by The-Grace-God** [comment]
Theme settings has been a problem before I believe I broke a table again but I would have to check it out

**Comment by The-Grace-God** [comment]
Odds are is most likely a table that doesn’t exist and the game is trying to change it

**Comment by The-Grace-God** [comment]
> When attempting to open the SLG(LUVM) menu the game instantly crashes not even an error comes up [crashinfo-1684289943.txt](https://github.com/The-Grace-God/Simply-Love-NotITG/files/11493575/crashinfo-1684289943.txt)
> 
> I get this error when the level select opens ![NotITG-v4 2 0_CBK8hOmTfT](https://user-images.githubusercontent.com/72986437/238814127-342f3905-00a4-4fee-8f52-7ea86bb7f2f9.png) It seems to do this every time the level select is updated while a level is on screen, If i go over to a section without any open levels there is no error and i can scroll freely The moment one is on screen it starts spamming the errors again and it locks one of the direction keys till their off screen again
> 
> There was also a thing about a command string that sometimes shows up when starting a level, but it seems random ![image](https://user-images.githubusercontent.com/72986437/238815046-2464dc0a-2135-4ca7-8ce0-33a9248c87b2.png)
> 
> And also this error comes up when the loading the end screen ![NotITG-v4 2 0_AZtfmyKynR](https://user-images.githubusercontent.com/72986437/238816033-07e339a5-126d-48f7-9492-981baa51e345.png)

I just realized your running 4.2.0 this theme requires in later builds 4.3.0

**Comment by The-Grace-God** [comment]
> When attempting to open the SLG(LUVM) menu the game instantly crashes not even an error comes up [crashinfo-1684289943.txt](https://github.com/The-Grace-God/Simply-Love-NotITG/files/11493575/crashinfo-1684289943.txt)
> 
> I get this error when the level select opens ![NotITG-v4 2 0_CBK8hOmTfT](https://user-images.githubusercontent.com/72986437/238814127-342f3905-00a4-4fee-8f52-7ea86bb7f2f9.png) It seems to do this every time the level select is updated while a level is on screen, If i go over to a section without any open levels there is no error and i can scroll freely The moment one is on screen it starts spamming the errors again and it locks one of the direction keys till their off screen again
> 
> There was also a thing about a command string that sometimes shows up when starting a level, but it seems random ![image](https://user-images.githubusercontent.com/72986437/238815046-2464dc0a-2135-4ca7-8ce0-33a9248c87b2.png)
> 
> And also this error comes up when the loading the end screen ![NotITG-v4 2 0_AZtfmyKynR](https://user-images.githubusercontent.com/72986437/238816033-07e339a5-126d-48f7-9492-981baa51e345.png)

Also quick tip the errors don't show up in Fullscreen but that problem will be fixed in v10 as that update is planned to be pretty large in terms of changes (as well as a more functional arcade mode)
